services:
  - type: worker
    name: cosmetics-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
